**Basic Python Assignment**

**1) Split this string**



In [3]:
s = "Hi there Shirin!"

In [4]:
s = "Hi there Shirin!"
x=s.split()
print(x)

['Hi', 'there', 'Shirin!']


**2) Use .format() to print the following string.**

**Output should be: The diameter of Earth is 12742 kilometers.**

In [5]:
planet = "Earth"
diameter = 12742
str=("The diameter of {planet} is {diameter} kilometers.")
print((str.format(planet="Earth",diameter=12742)))

The diameter of Earth is 12742 kilometers.


**3) In this nest dictionary grab the word "hello"**

In [6]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [7]:
d['k1'][-1]['tricky'][-1]['target'][-1]

'hello'

**4) Numpy**

In [8]:
import numpy as np

**4.1) Create an array of 10 zeros?**

**4.2) Create an array of 10 sevens?**

In [9]:
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
arr=np.ones(10)*7
print(arr)

[7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]


**5) Create an array of all the even integers from 20 to 35**

In [13]:
arr=np.arange(20,36,2)
print(arr)

[20 22 24 26 28 30 32 34]


**6) Create a 3x3 matrix with values ranging from 0 to 8**

In [14]:
arr=np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**7) Concatenate a and b**

**a = np.array([1, 2, 3]), b = np.array([4, 5, 6])**

In [15]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b),axis=None)

array([1, 2, 3, 4, 5, 6])

**Pandas**

**8) Create a dataframe with 3 rows and 2 columns**

In [16]:
import pandas as pd

In [17]:
pd.DataFrame({"Name":['Shirin','Jayapradha','Kiruthika','Banu'],"RollNo":[95071912049,95071912037,95071912045,95071912017]})

Name       RollNo
0      Shirin  95071912049
1  Jayapradha  95071912037
2   Kiruthika  95071912045
3        Banu  95071912017

**9) Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023**

In [18]:
pd.date_range(start="2023-01-01", end="2023-02-10")

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')

**10) Create 2D list to DataFrame**

In [19]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [20]:
pd.DataFrame(lists)

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24